Feat/mongo
claudioviniciuso/workeranalyzer pull request #4
Opened 2023-12-18 04:22 UTC by mhadaniya

Adicionando os métodos para MongoDB. 

@claudioviniciuso verificar se precisa de alterações.

2023-12-20 17:56 UTC, claudioviniciuso commented on worker_analyzer/storage.py
> +
if not self.status_connection:
            raise Exception("Connection is not active")

2023-12-20 17:57 UTC, claudioviniciuso requested changes
Mário,

Coloca por favor um raise no método save para caso a conexão tenha sido falha, ele não tente fazer o insert.

2023-12-21 05:31 UTC, mhadaniya commented
@claudioviniciuso  Adicionei o `raise` no método `save`. Adicionei testes para garantir, e também cobri outro ponto que achei que pode falhar também.

2023-12-22 18:26 UTC, claudioviniciuso approved these changes

2023-12-22 18:26 UTC, claudioviniciuso approved these changes

2023-12-22 18:26 UTC, merged